version: '3'
services:
  airflow-scraper:
    build: .
    container_name: kolesa_project
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/app/src
      - TZ=Asia/Almaty
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080